<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page import="com.sksu.model.Booking" %>
<%@ page import="com.sksu.controller.HomeController" %>
<%@ page import="java.util.List" %>
<!DOCTYPE html>
<%
      // --- DATA PREPARATION ---
    List<?> rawBookings = (List<?>) request.getAttribute("bookings");
    List<Booking> validBookings = new java.util.ArrayList<>();

    // Prepare helper map for resolving Room ID -> Room Name
    java.util.Map<String, String> roomMap = new java.util.HashMap<>();
    List<?> rawRooms = (List<?>) request.getAttribute("rooms");
    if (rawRooms != null) {
        for (Object obj : rawRooms) {
            if (obj instanceof com.sksu.model.Room) {
                com.sksu.model.Room r = (com.sksu.model.Room) obj;
                roomMap.put(r.getId(), r.getName());
            }
        }
    }

    if (rawBookings != null) {
        for (Object obj : rawBookings) {
            if (obj instanceof Booking) {
                validBookings.add((Booking) obj);
            }
        }
    }
%>
<html>
  <head>
    <title>SKSU Room Booking - Calendar</title>
    
    <!-- Bootstrap 5 CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
    <!-- Custom Theme CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="${pageContext.request.contextPath}/static/css/theme.css"
    />
  </head>
  <body class="page-layout">
    <%@ include file="includes/header.jsp" %>
    
    <div class="main-body-container">
      <%@ include file="includes/sidebar.jsp" %>

      <div class="content">
        <h1>Room Availability Calendar</h1>
        <p>View the monthly schedule for approved room usage.</p>

        <div class="card">
          <div class="calendar-controls">
            <button class="nav-button" onclick="navigateMonth(-1)">
              &#9664;
            </button>
            <h2 id="calendar-title"></h2>
            <button class="nav-button" onclick="navigateMonth(1)">
              &#9654;
            </button>

            <div class="view-buttons">
              <button class="btn btn-primary" onclick="changeView('month')">
                Month View
              </button>
            </div>
          </div>

          <%-- --- 1. MONTHLY VIEW (Content generated by JS) --- --%>
          <div
            id="calendar-month"
            class="calendar-grid calendar-monthly-grid"
            style="display: none"
          >
            <div class="month-header-cell">SUN</div>
            <div class="month-header-cell">MON</div>
            <div class="month-header-cell">TUE</div>
            <div class="month-header-cell">WED</div>
            <div class="month-header-cell">THU</div>
            <div class="month-header-cell">FRI</div>
            <div class="month-header-cell">SAT</div>

            <%-- Placeholder for JS content --%>
          </div>
        </div>
      </div>
    </div>

    <%-- --- MODAL STRUCTURE --- --%>
    <div id="bookingModal" class="modal">
      <div class="modal-content">
        <div class="modal-header">
          <h2>Booking Details</h2>
          <span class="close-button" onclick="closeModal()">&times;</span>
        </div>
        <div class="modal-body">
            <p><strong>Room:</strong> <span id="modalRoomName"></span></p>
            <p><strong>Room ID:</strong> <span id="modalRoomId"></span></p>
            <p><strong>Purpose:</strong> <span id="modalPurpose"></span></p>
            <p><strong>Date:</strong> <span id="modalDate"></span></p>
            <p><strong>Time:</strong> <span id="modalTime"></span></p>
            <p><strong>Status:</strong> <span id="modalStatus" style="font-weight: bold; color: green;"></span></p>
        </div>
      </div>
    </div>

    <%@ include file="includes/footer.jsp" %>

    <script>
      let currentView = 'month';
      let today = new Date();
      let currentMonth = today.getMonth();
      let currentYear = today.getFullYear();
      const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

      // --- FINAL FIX: Stable Data Structure for Calendar ---

      const mockBookings = [
      <%
          for (int i = 0; i < validBookings.size(); i++) {
              Booking booking = validBookings.get(i);

              String roomId = booking.getRoom();
              String roomName = roomMap.getOrDefault(roomId, "Room " + roomId); // Fallback if no name found
              String start = booking.getStart();
              String status = booking.getStatus();
              String purpose = booking.getPurpose();
              String formattedDate = HomeController.getBookingDate(start);

               // 2. Format Masa
               String startTime = "00:00";
               String endTime = "00:00";
               try {
                   // Parse Start Time
                   if (start.contains("T")) startTime = start.split("T")[1];
                   else if (start.contains(" ")) startTime = start.split(" ")[1];
                   if (startTime.length() > 5) startTime = startTime.substring(0, 5); // HH:mm
                   
                   // Parse End Time (Assuming booking.getEnd() exists and is populated)
                   String end = booking.getEnd();
                   if (end != null) {
                        if (end.contains("T")) endTime = end.split("T")[1];
                        else if (end.contains(" ")) endTime = end.split(" ")[1];
                        if (endTime.length() > 5) endTime = endTime.substring(0, 5); // HH:mm
                   }
                   
                   // Convert Start Time to AM/PM
                   int startHour = Integer.parseInt(startTime.substring(0, 2));
                   String startAmPm = startHour >= 12 ? "PM" : "AM";
                   startHour = startHour % 12;
                   if (startHour == 0) startHour = 12;
                   startTime = startHour + ":" + startTime.substring(3, 5) + " " + startAmPm;

                   // Convert End Time to AM/PM
                   if (!endTime.equals("00:00")) {
                       int endHour = Integer.parseInt(endTime.substring(0, 2));
                       String endAmPm = endHour >= 12 ? "PM" : "AM";
                       endHour = endHour % 12;
                       if (endHour == 0) endHour = 12;
                       endTime = endHour + ":" + endTime.substring(3, 5) + " " + endAmPm;
                       
                       startTime = startTime + " - " + endTime;
                   }
               } catch (Exception e) {
                   startTime = "Check details";
               }
      %>
              {
                  roomId: "<%= roomId %>",
                  roomName: "<%= roomName %>",
                  purpose: "<%= purpose %>",
                  time: "<%= startTime %>",
                  start: "<%= formattedDate %>",
                  status: "<%= status %>"
              }<%= (i < validBookings.size() - 1) ? "," : "" %>
      <%
          }
      %>
      ].sort((a, b) => a.time.localeCompare(b.time)); // Sort events by time on the day

      function changeView(view) {
          currentView = view;
          const month = document.getElementById('calendar-month');

          month.style.display = 'none';

          if (view === 'month') {
              month.style.display = 'grid';
              renderMonthlyView(currentYear, currentMonth);
          }
      }

      function navigateMonth(direction) {
          currentMonth += direction;
          if (currentMonth > 11) {
              currentMonth = 0;
              currentYear++;
          } else if (currentMonth < 0) {
              currentMonth = 11;
              currentYear--;
          }
          renderMonthlyView(currentYear, currentMonth);
      }

      function renderMonthlyView(year, month) {
          const container = document.getElementById('calendar-month');
          const firstDay = new Date(year, month, 1).getDay();
          const daysInMonth = new Date(year, month + 1, 0).getDate();

          while (container.children.length > 7) {
              container.removeChild(container.lastChild);
          }

          for (let i = 0; i < firstDay; i++) {
              const emptyCell = document.createElement('div');
              emptyCell.className = 'month-day-cell';
              container.appendChild(emptyCell);
          }

          for (let dayNum = 1; dayNum <= daysInMonth; dayNum++) {
              const cell = document.createElement('div');
              cell.className = 'month-day-cell';

              let content = '<span class="month-day-number">' + dayNum + '</span>';

              // Group events for the current day
              const dailyEvents = mockBookings.filter(booking => {
                  if (booking.status === 'Approved') { // ONLY show approved events
                      const [bYear, bMonth, bDay] = booking.start.split('-').map(Number);
                      return bYear === year && (bMonth - 1) === month && bDay === dayNum;
                  }
                  return false;
              });

              // Render filtered and sorted events
              dailyEvents.forEach(booking => {
                   const statusColor = '#D6C68B';
                   const textColor = '#556B2F';
                   
                   // Use Room Name for display
                   var eventText = booking.roomName;
                   
                   // ESCAPE DATA FOR ONCLICK
                   var jsRoomId = booking.roomId.replace(/'/g, "\\'").replace(/"/g, '&quot;');
                   var jsRoomName = booking.roomName.replace(/'/g, "\\'").replace(/"/g, '&quot;');
                   var jsPurpose = booking.purpose.replace(/'/g, "\\'").replace(/"/g, '&quot;');
                   var jsTime = booking.time;
                   var jsDate = booking.start;
                   var jsStatus = booking.status;

                   // Add onclick handler to open the modal
                   // Pass both Name and ID
                   content += '<div class="booking-event" ' +
                              'onclick="openModal(\'' + jsRoomName + '\', \'' + jsRoomId + '\', \'' + jsPurpose + '\', \'' + jsTime + '\', \'' + jsDate + '\', \'' + jsStatus + '\')" ' +
                              'style="background-color: ' + statusColor + '; color: ' + textColor + '; cursor: pointer;" ' +
                              'title="' + eventText.replace(/"/g, '&quot;') + '">' + 
                              eventText + 
                              '</div>';
              });

              cell.innerHTML = content;
              container.appendChild(cell);
          }

          document.getElementById('calendar-title').innerText = monthNames[month] + ' ' + year;
      }
      
      // --- MODAL FUNCTIONS ---
      function openModal(roomName, roomId, purpose, time, date, status) {
          document.getElementById('modalRoomName').innerText = roomName;
          document.getElementById('modalRoomId').innerText = roomId;
          document.getElementById('modalPurpose').innerText = purpose;
          document.getElementById('modalTime').innerText = time;
          document.getElementById('modalDate').innerText = date;
          document.getElementById('modalStatus').innerText = status;
          
          document.getElementById('bookingModal').style.display = "flex";
      }

      function closeModal() {
          document.getElementById('bookingModal').style.display = "none";
      }

      // Close modal if user clicks outside of it
      window.onclick = function(event) {
          var modal = document.getElementById('bookingModal');
          if (event.target == modal) {
              modal.style.display = "none";
          }
      }

      document.addEventListener('DOMContentLoaded', () => {
           changeView('month');
      });
    </script>
  </body>
</html>
